
package de.tum.ei.lkn.eces.tenantmanager.rerouting;

public enum CostIncreaseTypes {
    PHYSICAL_LINK_INCREASE,
    QUEUE_LINK_INCREASE,
    PHYSICAL_LINK_INCREASE_AND_SP,
    QUEUE_LINK_INCREASE_AND_SP,
    PHYSICAL_LINK_INCREASE_AND_ALL_SP,
    QUEUE_LINK_INCREASE_AND_ALL_SP,
    PHYSICAL_LINK_INCREASE_AND_ALL_TWO_SP,
    QUEUE_LINK_INCREASE_AND_ALL_TWO_SP,
}

